### ISSUE TITLE
MariaDB

### ISSUE THREAD

**Issue by pavelnemirovsky** [tarantool/mysql-tarantool-replication#14]
Hi,
can you please elaborate why MariaDB (based on mysql 5.6) is not supported?
Thanks in advance,
P

**Comment by smarek** [comment]
FYI MariaDB solution https://gist.github.com/smarek/d88a870128cdda948be70eb3f93d4c92

**Comment by pavelnemirovsky** [comment]
@smarek thx a lot

**Comment by Totktonada** [comment]
Duplicate of #4.
