### ISSUE TITLE
Составной первичный ключ и типы полей

### ISSUE THREAD

**Issue by sergio-zerg** [tarantool/mysql-tarantool-replication#17]
Добрый день.
Обнаружил несколько проблем:
1 - репликация не происходит, если тип поля в MySQL decimal.
В лог репликатора падает следующая ошибка E Error in reading binlogs: Slave::create_table(): error in field 'value'
2 - с типом char то же самое.
При смене типов на float и varchar ошибка пропадает
3 - При первом запуске(если поменять типы полей на указанные) записи из таблицы trend реплицируются в соответствующий спейс,
но далее, при изменении, добавлении или удалении записей в БД в спейсе ничего не меняется.

MySQL

CREATE TABLE `trend` (
  `date` date NOT NULL,
  `code` varchar(8) NOT NULL,
  `value` decimal(10,4) unsigned NOT NULL,
  `delta` decimal(10,4) NOT NULL,
  `trend` char(7) NOT NULL,
  `name` varchar(20) NOT NULL,
  PRIMARY KEY (`date`,`code`),
  UNIQUE KEY `idx_unique_currency` (`date`,`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

Tarantool

local trends = box.schema.space.create('trends', {id=9, field_count=6});
trends:create_index('primary', {parts = {1, 'string', 2, 'string'}});

replicator.yml - кусок

    - database: test
      table: trend
      columns: [date, code, value, delta, trend, name]
      space: 9
      key_fields: [ 0, 1 ]

**Comment by sergio-zerg** [comment]
Я также вешал в репликаторе колбеки такого вида 
function log1(data)
            log.info(data)
              return true
end
и смотрел в лог тарантула.
видно, что измененная запись приходит.
Но не меняется в самом спейсе

**Comment by Totktonada** [comment]
Splitted to several tasks: #36, #37, #38.
