### ISSUE TITLE
What is binlog_pos_key?

### ISSUE THREAD

**Issue by mskrish20** [tarantool/mysql-tarantool-replication#25]
What should be replaced with binlog_pos_key in main.cpp?

**Comment by darrenchinesedba** [comment]
i hope to know also i can find the space like binlog_pos_space: 512 but i can find    binlog_pos_key

box.space.mysqldata:select()
---
- []
...
nothing in this binlog_pos_space

**Comment by Totktonada** [comment]
See the [README.md](https://github.com/tarantool/mysql-tarantool-replication/blob/846802e32d00d350fdfcebd462f570beb1b90495/README.md#replicator-configuration):

> Set `binlog_pos_space` to the space id created for the replication state and `binlog_pos_key` to identify the corresponding tuple in a given space.

It is the primary key of the tuple where a binlog position will be stored. Usually zero.

The only reason to set it to a non-zero value, as I see, is when several mysql instances are replicated into one tarantool instance and so different binlog positions should be stored in tarantool.

**Comment by Totktonada** [comment]
Feel free to reopen the issue and clarify the question if something is still unclear.
