### ISSUE TITLE
issue about transfer mysql 8.0.20 to tarantool 2.4.1

### ISSUE THREAD

**Issue by darrenchinesedba** [tarantool/mysql-tarantool-replication#29]
i have 3 question for the topic

一、first, E Slave::create_table(): class name don't exist for type: 246
[2020-07-03 12:03:32] E Error in reading binlogs: Slave::create_table(): error in field 'bet_money'

Alexander give me the reply
https://github.com/tarantool/libslave/pull/5/commits/453fa49698ac625f47063943f52be7ae2ad8f93d
https://github.com/tarantool/mysql-tarantool-replication/issues/18#issuecomment-653239323

i try servral time,but no sucessful ,i need to try more

二、second, E Met exception in get_remote_binlog cycle. Message: regex_error
In case the tarantool already has data, the tarantool cannot continue to transfer new data by using  replicatord

三、how to find binlog_pos_key
i hope to know also i can find the space like binlog_pos_space: 512 but i can find binlog_pos_key

box.space.mysqldata:select()
[]
...
nothing in this binlog_pos_space

**Comment by Totktonada** [comment]
1. Tracked by #18. We discussing it offline with @darrenchinesedba.
2. Tracked by #19.
3. No binlog position is written. Looks as the effect of the errors above.

**Comment by Totktonada** [comment]
Since all mentioned problems have its own issues, I'll close this one.
